### ISSUE TITLE
API Requests don't work with HTTP Proxy

### ISSUE THREAD

**Issue by eric-kennedy** [workarea-commerce/workarea-listrak#2]
**HTTP Proxy not used**
Staging/Production environments use an HTTP Proxy for outgoing requests, and the Listrak API requests made by Net::HTTP are not being routed through the proxy.  It's supposed to use the proxy configured by the environment variables set up on the server.

**To Reproduce**
1. Install Listrak plugin
2. Deploy to Staging environment or configure a HTTP proxy locally
3. Configure Listrak secrets
4. Go to /admin and select the Listrak Config page from the admin menu
5. Page will show a 500 error and log will show a Net::HTTP connection timeout

**Expected behavior**
Page loads and successfully requests supporting data from the Listrak REST API

**Workarea Setup (please complete the following information):**
 - Workarea Version: v3.3.35
 - Plugins:
   - workarea-commerce_cloud
   - workarea-content_search
   - workarea-multi_site
   - workarea-basic_auth
   - workarea-sentry
   - workarea-mach
   - workarea-reviews
   - workarea-share
   - workarea-super_hero
   - workarea-product_quickview
   - workarea-mini_cart
   - workarea-import
   - workarea-shipping_estimation
   - workarea-paypal
   - workarea-sticky
   - workarea-shipping_message
   - workarea-filter_dropdowns
   - workarea-google_analytics
   - workarea-google_tag_manager
   - workarea-sitemaps
   - workarea-flow_io
   - workarea-slick_slider
   - workarea-core
   - workarea-storefront
   - workarea-admin
   - workarea-testing
   - workarea-accordions
   - workarea-listrak

**Additional context**
From slack: "looks like HTTP.post_form uses HTTP.start and passes p_adder as nil so the default arg in HTTP.new  of p_addr = :ENV gets overwritten."

**Comment by tubbo** [comment]
Hey @eric-kennedy, can you try depending on the branch we made in `Gemfile` to see if it fixes anything? You'll have to deploy it to really see changes.

```ruby
gem 'workarea-listrak',
  github: 'workarea-commerce/workarea-listrak',
  branch: 'LISTRAK-1-fix-proxy-usage'
```

**Comment by eric-kennedy** [comment]
We already patched in a fix and are testing it on the staging site, so I can't pull in your change right now.  I looked at your pull request though, and it looks right.
Thanks!
