### ISSUE TITLE
Configuration of the javascript merchant id doesn't work with Multi Site

### ISSUE THREAD

**Issue by eric-kennedy** [workarea-commerce/workarea-listrak#3]
**Configuration is compiled with the Default site config**
Staging/Production environments use a js uglifier to compile the js and the configuration defined in app/assets/javascripts/workarea/storefront/listrak/listrak_config.js.erb gets included in that.  The compiled js gets the config settings from the default workarea config, so you can't set a different merchant id for each site.

**To Reproduce**
1. Install Listrak plugin on an app set up for multi-site 
2. Replace development setting `config.assets.debug = true` with `config.assets.js_compressor = :uglifier`
3. Configure a different listrak merchant id for each site `config.listrak.analytics = { merchant_id: 'ID' }`
4. Run the site and open the browser's developer console and run `WORKAREA.config.listrak` to see that the merchant id is coming from the default site instead of the current site.

**Expected behavior**
The Javascript uses the correct merchant id for each site on multi_site

**Workarea Setup (please complete the following information):**
 - Workarea Version: v3.3.35
 - Plugins:
   - workarea-commerce_cloud
   - workarea-content_search
   - workarea-multi_site
   - workarea-basic_auth
   - workarea-sentry
   - workarea-mach
   - workarea-reviews
   - workarea-share
   - workarea-super_hero
   - workarea-product_quickview
   - workarea-mini_cart
   - workarea-import
   - workarea-shipping_estimation
   - workarea-paypal
   - workarea-sticky
   - workarea-shipping_message
   - workarea-filter_dropdowns
   - workarea-google_analytics
   - workarea-google_tag_manager
   - workarea-sitemaps
   - workarea-flow_io
   - workarea-slick_slider
   - workarea-core
   - workarea-storefront
   - workarea-admin
   - workarea-testing
   - workarea-accordions
   - workarea-listrak

**Comment by tubbo** [comment]
@eric-kennedy Using JS integrations that depend on multi-site configuration requires a manifest for each site. Do you have a separate JS manifest configured for each site already? If you don't, use the `workarea:site` generator to generate the required files. The multi-site plugin redefines `assets:precompile` to loop over all sites and compile each JS manifest using the proper site ID, so if you have multiple manifests, this should work without much (if any) intervention.

**Comment by eric-kennedy** [comment]
@tubbo, We weren't using separate JS manifests.  All the sites have been using the same javascript features, so we haven't had to differentiate it.  Thanks for the clarification.
